Disable adding/removed assessment from structured data
Disable adding or removing the ‘Commons quality assessment’ (P6731)
claim ‘Wikimedia Commons featured picture’ (Q63348049) to/from the
structured data (media info).  It worked very well until yesterday,
but since the first run of the bot program on this morning (1 April
2026) every attempt fails with a Pywikibot MaxlagTimeoutError
exception: ‘Maximum retries attempted due to maxlag without success’.

If I run the bot program locally, the result is the same, or I get
a ConnectionError from the ‘requests’ library (which is used by
Pywikibot for its HTTP connections) with the message: ‘Remote end
closed connection without response’.

I guess that the configuration of the server or something similar
was changed and that the changes took effect from this morning.
I will fix and re-enable the feature when I can figure out what
was wrong resp. what needs to be changed in our code.